# kserve/minio-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-minio-sa
  namespace: default
secrets:
  - name: minio-creds
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-rf
  namespace: default
spec:
  predictor:
    serviceAccountName: kserve-minio-sa
    sklearn:
      storageUri: s3://mlflow/sklearn-model/randomforest